platform :ios, '8.0'
inhibit_all_warnings!

target 'IrregularCollectionUIKit_Example' do
  pod 'IrregularCollectionUIKit', :path => '../'

  target 'IrregularCollectionUIKit_Tests' do
    inherit! :search_paths

    
  end
end
