language: swift
osx_image: xcode8.3
script: set -o pipefail && xcodebuild -workspace Example/IrregularCollectionUIKit.xcworkspace -scheme IrregularCollectionUIKit_Example -sdk iphonesimulator10.3 | xcpretty
